const THEME_KEY="mm-theme";
(function(){const saved=localStorage.getItem(THEME_KEY);if(saved==="dark"||saved==="light")document.documentElement.setAttribute("data-theme",saved)})();
export function initTheme(){const toggle=document.getElementById("theme-toggle");if(!toggle)return;toggle.addEventListener("click",()=>{const current=document.documentElement.getAttribute("data-theme")==="dark"?"dark":"light";const next=current==="dark"?"light":"dark";document.documentElement.setAttribute("data-theme",next);localStorage.setItem(THEME_KEY,next)})}
export function initNavbar(activePage){const links=[{href:"index.html",label:"Beranda",key:"beranda"},{href:"lagu.html",label:"Kumpulan Lagu",key:"lagu"},{href:"panduan.html",label:"Panduan Multimedia",key:"panduan"},{href:"jadwal.html",label:"Jadwal Multimedia",key:"jadwal"}];const nav=document.getElementById("site-nav");if(!nav)return;nav.innerHTML=`<div class="nav-inner"><a href="index.html" class="nav-brand"><span class="nav-brand-mark"><img src="assets/logo.png" alt="Logo Multimedia"></span><span class="nav-brand-text">Multimedia</span></a><span class="nav-brand-sub">Gereja Toraja Jemaat Batam Centre</span></span></a><div class="nav-links" id="nav-links">${links.map(l=>`<a href="${l.href}" class="nav-link${l.key===activePage?" is-active":""}">${l.label}</a>`).join("")}</div><div class="nav-right"><button class="theme-toggle" id="theme-toggle" aria-label="Ganti tema"><svg class="icon-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg><svg class="icon-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="4.5"/><path d="M12 2.5v2.5M12 19v2.5M4.2 4.2l1.8 1.8M18 18l1.8 1.8M2.5 12H5M19 12h2.5"/></svg></button><button class="nav-toggle" id="nav-toggle" aria-label="Buka menu" aria-expanded="false"><span></span><span></span><span></span></button></div></div>`;const toggle=document.getElementById("nav-toggle"),linksEl=document.getElementById("nav-links");toggle.addEventListener("click",()=>{const open=linksEl.classList.toggle("is-open");toggle.setAttribute("aria-expanded",String(open))});linksEl.querySelectorAll(".nav-link").forEach(a=>a.addEventListener("click",()=>{linksEl.classList.remove("is-open");toggle.setAttribute("aria-expanded","false")}));initTheme()}
export function initFooter(){const footer=document.getElementById("site-footer");if(!footer)return;footer.innerHTML=`<div class="footer-inner"><p>&copy; ${new Date().getFullYear()} Tim Multimedia · Gereja Toraja Jemaat Batam Centre</p></div>`}
export function renderLoading(container,message="Memuat data..."){container.innerHTML=`<div class="state-box state-loading"><div class="spinner"></div><p>${message}</p></div>`}
export function renderEmpty(container,message="Belum ada data.",hint=""){container.innerHTML=`<div class="state-box state-empty"><p class="state-title">${message}</p>${hint?`<p class="state-hint">${hint}</p>`:""}</div>`}
export function renderError(container,message="Gagal memuat data."){container.innerHTML=`<div class="state-box state-error"><p class="state-title">Terjadi kesalahan</p><p class="state-hint">${message}</p></div>`}
export function debounce(fn,delay=250){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay)}}
export function escapeHtml(str=""){return String(str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
export function formatTanggal(value){let date;if(!value)return"-";date=typeof value.toDate==="function"?value.toDate():new Date(value);if(isNaN(date.getTime()))return String(value);return date.toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
export function toDateObj(value){if(!value)return null;if(typeof value.toDate==="function")return value.toDate();const d=new Date(value);return isNaN(d.getTime())?null:d}